GENERAL_CAREER_SIGNALS = [
    "hướng nghiệp",
    "tìm hiểu nghề",
    "tìm hiểu ngành",
    "chọn nghề",
    "chọn ngành",
    "ngành học",
    "ngành nghề",
    "nghề nghiệp",
    "nghề này",
    "nghề đó",
    "nghề trên",
    "nghề thứ nhất",
    "nghề thứ hai",
    "nghề được gợi ý",
    "ngành được gợi ý",
    "gợi ý nghề",
    "career",
    "career path",
    "roadmap",
    "lộ trình",
    "assessment",
    "đánh giá năng lực",
    "công việc phù hợp",
    "ít giao tiếp",
    "hướng nội",
    "làm việc với máy tính",
    "thích vẽ",
    "đại học",
    "trường",
    "điểm chuẩn",
    "học phí",
    "xét tuyển",
    "tổ hợp môn",
    "điểm ngành",
    "điểm tuyển sinh",
    "điểm trúng tuyển",
    "nguyện vọng",
    "khối thi",
    "học bổng",
    "du học",
    "thực tập",
    "internship",
    "CV",
    "portfolio",
    "phỏng vấn",
    "kỹ năng",
    "sở thích",
    "điểm mạnh",
    "điểm yếu",
    "mục tiêu nghề nghiệp",
    "mục tiêu",
    "tương lai",
    "việc làm",
    "mức lương",
    "chuyển ngành",
]

DYNAMIC_CAREER_TITLES = ()


DEFAULT_CAREER_TITLES = [
    # AI, Data and IT
    "Chuyên viên phân tích dữ liệu",
    "Nhà khoa học dữ liệu",
    "Kỹ sư dữ liệu",
    "Kỹ sư học máy",
    "Kỹ sư trí tuệ nhân tạo",
    "Chuyên viên phân tích kinh doanh",
    "Chuyên viên phân tích nghiệp vụ",
    "Chuyên viên BI",
    "Chuyên viên dữ liệu giáo dục",
    "Kỹ sư phần mềm",
    "Lập trình viên frontend",
    "Lập trình viên backend",
    "Lập trình viên full-stack",
    "Lập trình viên ứng dụng di động",
    "Kỹ sư DevOps",
    "Kỹ sư điện toán đám mây",
    "Chuyên viên an ninh mạng",
    "Kiểm thử viên phần mềm",
    "Quản trị cơ sở dữ liệu",
    "Quản trị hệ thống",
    "Kỹ sư IoT",
    "Kỹ sư nhúng",
    "Chuyên viên thiết kế UI",
    "Chuyên viên thiết kế UX",
    "Quản lý sản phẩm",
    "Scrum Master",
    "Kỹ sư blockchain",
    "Chuyên viên hỗ trợ kỹ thuật",
    "Chuyên viên quản trị mạng",
    # Engineering and manufacturing
    "Kỹ sư cơ khí",
    "Kỹ sư điện",
    "Kỹ sư điện tử",
    "Kỹ sư tự động hóa",
    "Kỹ sư điều khiển",
    "Kỹ sư xây dựng",
    "Kỹ sư cầu đường",
    "Kỹ sư bán dẫn",
    "Kỹ sư vật liệu",
    "Kỹ sư hóa học",
    "Kỹ sư công nghiệp",
    "Kỹ sư sản xuất",
    "Kỹ sư chất lượng",
    "Kỹ sư bảo trì",
    "Kỹ sư năng lượng tái tạo",
    "Kỹ sư môi trường",
    "Kỹ sư hàng không",
    "Kỹ sư cơ điện tử",
    "Kỹ sư an toàn lao động",
    "Kỹ sư thiết kế cơ khí",
    # Business and finance
    "Kế toán",
    "Kiểm toán viên",
    "Chuyên viên tài chính",
    "Chuyên viên ngân hàng",
    "Chuyên viên đầu tư",
    "Chuyên viên quản trị rủi ro",
    "Chuyên viên bảo hiểm",
    "Chuyên viên kinh doanh",
    "Quản lý bán hàng",
    "Chuyên viên nhân sự",
    "Chuyên viên tuyển dụng",
    "Chuyên viên thương mại điện tử",
    "Chuyên viên vận hành thương mại điện tử",
    "Chuyên viên vận hành",
    "Tư vấn quản lý",
    "Quản lý dự án",
    "Chuyên viên chăm sóc khách hàng",
    "Chuyên viên nghiên cứu thị trường",
    # Marketing and communication
    "Chuyên viên marketing số",
    "Chuyên viên marketing nội dung",
    "Chuyên viên SEO",
    "Chuyên viên truyền thông",
    "Chuyên viên quan hệ công chúng",
    "Chuyên viên sáng tạo nội dung",
    "Biên tập viên nội dung",
    "Nhà báo",
    "Copywriter",
    "Quản lý thương hiệu",
    "Chuyên viên quảng cáo",
    "Chuyên viên mạng xã hội",
    "Nhà sản xuất video",
    # Health and wellness
    "Bác sĩ",
    "Dược sĩ",
    "Điều dưỡng",
    "Bác sĩ thú y",
    "Chuyên viên dinh dưỡng",
    "Chuyên viên y tế công cộng",
    "Kỹ thuật viên xét nghiệm y học",
    "Kỹ thuật viên chẩn đoán hình ảnh",
    "Nhà vật lý trị liệu",
    "Chuyên viên tâm lý",
    "Chuyên viên tư vấn học đường",
    "Bác sĩ nha khoa",
    "Hộ sinh",
    "Kỹ sư công nghệ sinh học",
    # Education, language and social work
    "Giáo viên mầm non",
    "Giáo viên tiểu học",
    "Giáo viên trung học",
    "Giảng viên đại học",
    "Chuyên viên giáo dục",
    "Chuyên viên công tác xã hội",
    "Chuyên viên đào tạo",
    "Chuyên viên thiết kế học liệu",
    "Nhà nghiên cứu giáo dục",
    "Phiên dịch viên",
    "Biên dịch viên",
    # Law, public administration and international relations
    "Luật sư",
    "Chuyên viên pháp lý",
    "Công chứng viên",
    "Chuyên viên hành chính",
    "Chuyên viên chính sách công",
    "Cán bộ ngoại giao",
    "Chuyên viên quan hệ quốc tế",
    "Chuyên viên quản lý nhà nước",
    # Design and creative careers
    "Nhà thiết kế đồ họa",
    "Nhà thiết kế đa phương tiện",
    "Nhà thiết kế sản phẩm số",
    "Nhà thiết kế nội thất",
    "Nhà thiết kế thời trang",
    "Nhà thiết kế game",
    "Họa sĩ minh họa",
    "Nhiếp ảnh gia",
    "Đạo diễn",
    "Nhà sản xuất âm nhạc",
    "Nhà thiết kế sản phẩm",
    "Kiến trúc sư",
    # Science and research
    "Nhà nghiên cứu khoa học vật liệu",
    "Nhà nghiên cứu sinh học",
    "Nhà hóa học",
    "Nhà vật lý",
    "Nhà toán học ứng dụng",
    "Chuyên viên thống kê",
    "Chuyên viên GIS",
    "Nhà nghiên cứu môi trường",
    "Kỹ thuật viên phòng thí nghiệm",
    # Logistics, tourism and services
    "Chuyên viên chuỗi cung ứng",
    "Chuyên viên logistics",
    "Nhân viên xuất nhập khẩu",
    "Điều phối viên vận tải",
    "Quản lý kho",
    "Hướng dẫn viên du lịch",
    "Quản trị khách sạn",
    "Quản lý nhà hàng",
    "Đầu bếp",
    "Quản lý ẩm thực",
    "Tiếp viên hàng không",
    # Agriculture, environment and food
    "Kỹ sư nông nghiệp",
    "Kỹ sư công nghệ thực phẩm",
    "Chuyên viên an toàn thực phẩm",
    "Kỹ sư thủy sản",
    "Chuyên viên quản lý tài nguyên môi trường",
    "Chuyên viên phát triển bền vững",
    "Kỹ sư lâm nghiệp",
    "Chuyên viên kiểm nghiệm thực phẩm",
    "Quản lý trang trại",
    "Chuyên viên bảo tồn thiên nhiên",
]


CAREER_ALIASES = {
    "data analyst": "Chuyên viên phân tích dữ liệu",
    "da": "Chuyên viên phân tích dữ liệu",
    "nhân viên phân tích dữ liệu": "Chuyên viên phân tích dữ liệu",
    "chuyên viên data": "Chuyên viên phân tích dữ liệu",
    "phân tích dữ liệu": "Chuyên viên phân tích dữ liệu",
    "data scientist": "Nhà khoa học dữ liệu",
    "khoa học dữ liệu": "Nhà khoa học dữ liệu",
    "education data scientist": "Chuyên viên dữ liệu giáo dục",
    "khoa học dữ liệu giáo dục": "Chuyên viên dữ liệu giáo dục",
    "data engineer": "Kỹ sư dữ liệu",
    "machine learning engineer": "Kỹ sư học máy",
    "ml engineer": "Kỹ sư học máy",
    "ai/ml engineer": "Kỹ sư học máy",
    "AI/Machine Learning Engineer": "Kỹ sư học máy",
    "ml": "Kỹ sư học máy",
    "ai engineer": "Kỹ sư trí tuệ nhân tạo",
    "kỹ sư ai": "Kỹ sư trí tuệ nhân tạo",
    "ai": "Kỹ sư trí tuệ nhân tạo",
    "business analyst": "Chuyên viên phân tích kinh doanh",
    "ba": "Chuyên viên phân tích kinh doanh",
    "chuyên viên phân tích nghiệp vụ": "Chuyên viên phân tích kinh doanh",
    "phân tích nghiệp vụ": "Chuyên viên phân tích kinh doanh",
    "business intelligence analyst": "Chuyên viên BI",
    "bi analyst": "Chuyên viên BI",
    "business intelligence": "Chuyên viên BI",
    "software engineer": "Kỹ sư phần mềm",
    "software developer": "Kỹ sư phần mềm",
    "developer": "Kỹ sư phần mềm",
    "lập trình": "Kỹ sư phần mềm",
    "lập trình viên": "Kỹ sư phần mềm",
    "nghề code": "Kỹ sư phần mềm",
    "se": "Kỹ sư phần mềm",
    "frontend": "Lập trình viên frontend",
    "frontend developer": "Lập trình viên frontend",
    "front-end developer": "Lập trình viên frontend",
    "frontend engineer": "Lập trình viên frontend",
    "front-end engineer": "Lập trình viên frontend",
    "backend": "Lập trình viên backend",
    "backend developer": "Lập trình viên backend",
    "back-end developer": "Lập trình viên backend",
    "backend engineer": "Lập trình viên backend",
    "full-stack developer": "Lập trình viên full-stack",
    "fullstack developer": "Lập trình viên full-stack",
    "mobile app developer": "Lập trình viên ứng dụng di động",
    "mobile developer": "Lập trình viên ứng dụng di động",
    "android developer": "Lập trình viên ứng dụng di động",
    "ios developer": "Lập trình viên ứng dụng di động",
    "devops engineer": "Kỹ sư DevOps",
    "cloud/devops engineer": "Kỹ sư DevOps",
    "cloud engineer": "Kỹ sư điện toán đám mây",
    "cybersecurity analyst": "Chuyên viên an ninh mạng",
    "security analyst": "Chuyên viên an ninh mạng",
    "quality assurance": "Kiểm thử viên phần mềm",
    "qa engineer": "Kiểm thử viên phần mềm",
    "qa": "Kiểm thử viên phần mềm",
    "tester": "Kiểm thử viên phần mềm",
    "software tester": "Kiểm thử viên phần mềm",
    "database administrator": "Quản trị cơ sở dữ liệu",
    "dba": "Quản trị cơ sở dữ liệu",
    "system administrator": "Quản trị hệ thống",
    "sysadmin": "Quản trị hệ thống",
    "network administrator": "Chuyên viên quản trị mạng",
    "iot engineer": "Kỹ sư IoT",
    "embedded engineer": "Kỹ sư nhúng",
    "kỹ sư iot/embedded": "Kỹ sư IoT",
    "ui designer": "Chuyên viên thiết kế UI",
    "ui": "Chuyên viên thiết kế UI",
    "ux designer": "Chuyên viên thiết kế UX",
    "ux": "Chuyên viên thiết kế UX",
    "ux/ui designer": "Chuyên viên thiết kế UX",
    "ui/ux designer": "Chuyên viên thiết kế UX",
    "product manager": "Quản lý sản phẩm",
    "product owner": "Quản lý sản phẩm",
    "pm": "Quản lý sản phẩm",
    "scrum master": "Scrum Master",
    "blockchain engineer": "Kỹ sư blockchain",
    "technical support": "Chuyên viên hỗ trợ kỹ thuật",
    "mechanical engineer": "Kỹ sư cơ khí",
    "electrical engineer": "Kỹ sư điện",
    "electronics engineer": "Kỹ sư điện tử",
    "automation engineer": "Kỹ sư tự động hóa",
    "civil engineer": "Kỹ sư xây dựng",
    "semiconductor engineer": "Kỹ sư bán dẫn",
    "materials scientist": "Nhà nghiên cứu khoa học vật liệu",
    "materials engineer": "Kỹ sư vật liệu",
    "chemical engineer": "Kỹ sư hóa học",
    "industrial engineer": "Kỹ sư công nghiệp",
    "manufacturing engineer": "Kỹ sư sản xuất",
    "quality engineer": "Kỹ sư chất lượng",
    "maintenance engineer": "Kỹ sư bảo trì",
    "renewable energy engineer": "Kỹ sư năng lượng tái tạo",
    "environmental engineer": "Kỹ sư môi trường",
    "mechatronics engineer": "Kỹ sư cơ điện tử",
    "accountant": "Kế toán",
    "auditor": "Kiểm toán viên",
    "financial analyst": "Chuyên viên tài chính",
    "finance specialist": "Chuyên viên tài chính",
    "banking officer": "Chuyên viên ngân hàng",
    "investment analyst": "Chuyên viên đầu tư",
    "risk analyst": "Chuyên viên quản trị rủi ro",
    "sales executive": "Chuyên viên kinh doanh",
    "sales manager": "Quản lý bán hàng",
    "human resources": "Chuyên viên nhân sự",
    "hr": "Chuyên viên nhân sự",
    "recruiter": "Chuyên viên tuyển dụng",
    "talent acquisition": "Chuyên viên tuyển dụng",
    "e-commerce operations specialist": "Chuyên viên vận hành thương mại điện tử",
    "ecommerce operations": "Chuyên viên vận hành thương mại điện tử",
    "operations specialist": "Chuyên viên vận hành",
    "management consultant": "Tư vấn quản lý",
    "project manager": "Quản lý dự án",
    "customer success": "Chuyên viên chăm sóc khách hàng",
    "customer service": "Chuyên viên chăm sóc khách hàng",
    "market researcher": "Chuyên viên nghiên cứu thị trường",
    "digital marketing specialist": "Chuyên viên marketing số",
    "digital marketer": "Chuyên viên marketing số",
    "làm marketing": "Chuyên viên marketing số",
    "seo specialist": "Chuyên viên SEO",
    "communications specialist": "Chuyên viên truyền thông",
    "public relations specialist": "Chuyên viên quan hệ công chúng",
    "pr specialist": "Chuyên viên quan hệ công chúng",
    "content creator": "Chuyên viên sáng tạo nội dung",
    "content writer": "Biên tập viên nội dung",
    "copywriter": "Copywriter",
    "brand manager": "Quản lý thương hiệu",
    "social media specialist": "Chuyên viên mạng xã hội",
    "video producer": "Nhà sản xuất video",
    "doctor": "Bác sĩ",
    "physician": "Bác sĩ",
    "pharmacist": "Dược sĩ",
    "nurse": "Điều dưỡng",
    "veterinarian": "Bác sĩ thú y",
    "vet": "Bác sĩ thú y",
    "nutritionist": "Chuyên viên dinh dưỡng",
    "public health specialist": "Chuyên viên y tế công cộng",
    "medical laboratory technician": "Kỹ thuật viên xét nghiệm y học",
    "radiology technician": "Kỹ thuật viên chẩn đoán hình ảnh",
    "physical therapist": "Nhà vật lý trị liệu",
    "psychologist": "Chuyên viên tâm lý",
    "school counselor": "Chuyên viên tư vấn học đường",
    "dentist": "Bác sĩ nha khoa",
    "midwife": "Hộ sinh",
    "biotechnology engineer": "Kỹ sư công nghệ sinh học",
    "teacher": "Giáo viên trung học",
    "lecturer": "Giảng viên đại học",
    "education specialist": "Chuyên viên giáo dục",
    "social worker": "Chuyên viên công tác xã hội",
    "training specialist": "Chuyên viên đào tạo",
    "instructional designer": "Chuyên viên thiết kế học liệu",
    "translator": "Biên dịch viên",
    "interpreter": "Phiên dịch viên",
    "lawyer": "Luật sư",
    "legal specialist": "Chuyên viên pháp lý",
    "notary": "Công chứng viên",
    "administrative officer": "Chuyên viên hành chính",
    "policy analyst": "Chuyên viên chính sách công",
    "diplomat": "Cán bộ ngoại giao",
    "international relations specialist": "Chuyên viên quan hệ quốc tế",
    "graphic designer": "Nhà thiết kế đồ họa",
    "multimedia designer": "Nhà thiết kế đa phương tiện",
    "product designer": "Nhà thiết kế sản phẩm số",
    "digital product designer": "Nhà thiết kế sản phẩm số",
    "interior designer": "Nhà thiết kế nội thất",
    "fashion designer": "Nhà thiết kế thời trang",
    "game designer": "Nhà thiết kế game",
    "game developer": "Nhà thiết kế game",
    "làm game": "Nhà thiết kế game",
    "phát triển game": "Nhà thiết kế game",
    "illustrator": "Họa sĩ minh họa",
    "photographer": "Nhiếp ảnh gia",
    "director": "Đạo diễn",
    "music producer": "Nhà sản xuất âm nhạc",
    "architect": "Kiến trúc sư",
    "biologist": "Nhà nghiên cứu sinh học",
    "chemist": "Nhà hóa học",
    "physicist": "Nhà vật lý",
    "applied mathematician": "Nhà toán học ứng dụng",
    "statistician": "Chuyên viên thống kê",
    "gis specialist": "Chuyên viên GIS",
    "lab technician": "Kỹ thuật viên phòng thí nghiệm",
    "supply chain specialist": "Chuyên viên chuỗi cung ứng",
    "supply chain": "Chuyên viên chuỗi cung ứng",
    "logistics/supply chain specialist": "Chuyên viên chuỗi cung ứng",
    "logistics specialist": "Chuyên viên logistics",
    "import export specialist": "Nhân viên xuất nhập khẩu",
    "warehouse manager": "Quản lý kho",
    "tour guide": "Hướng dẫn viên du lịch",
    "hotel manager": "Quản trị khách sạn",
    "restaurant manager": "Quản lý nhà hàng",
    "chef": "Đầu bếp",
    "flight attendant": "Tiếp viên hàng không",
    "agricultural engineer": "Kỹ sư nông nghiệp",
    "food technology engineer": "Kỹ sư công nghệ thực phẩm",
    "food technologist": "Kỹ sư công nghệ thực phẩm",
    "food safety specialist": "Chuyên viên an toàn thực phẩm",
    "aquaculture engineer": "Kỹ sư thủy sản",
    "sustainability specialist": "Chuyên viên phát triển bền vững",
    "forestry engineer": "Kỹ sư lâm nghiệp",
    "farm manager": "Quản lý trang trại",
    "conservation specialist": "Chuyên viên bảo tồn thiên nhiên",
    "làm dữ liệu": "Chuyên viên phân tích dữ liệu",
    "nghề dữ liệu": "Chuyên viên phân tích dữ liệu",
    "làm kinh doanh": "Chuyên viên kinh doanh",
    "làm thiết kế": "Nhà thiết kế đồ họa",
}
